import 'package:flutter/material.dart';
import 'package:one/model/UserModel/usermodel.dart';
import 'package:one/view_model/imageprovider.dart';
import 'package:one/view_model/userproivder.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class Addpage extends StatelessWidget {
  Addpage({super.key});
  TextEditingController username = TextEditingController();
  TextEditingController password = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('add page'),
        backgroundColor: Colors.blue,
      ),
      body: Consumer2<Userproivder, ImageProviders>(
        builder: (context, value, imageprovider, child) => SafeArea(
            child: Padding(
          padding: const EdgeInsets.only(left: 30, right: 30),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            spacing: 30,
            children: [
              GestureDetector(
                onTap: () {
                  imageprovider.pickImage();
                },
                child: CircleAvatar(
                  radius: 50,
                  backgroundImage: imageprovider.imageFile != null
                      ? FileImage(imageprovider.imageFile!)
                      : null,
                  child: imageprovider.imageFile == null
                      ? Icon(Icons.person, size: 50)
                      : null,
                ),
              ),
              TextField(
                controller: username,
                decoration: InputDecoration(
                    hintText: 'userName', border: OutlineInputBorder()),
              ),
              TextField(
                controller: password,
                decoration: InputDecoration(
                    hintText: 'password', border: OutlineInputBorder()),
              ),
              ElevatedButton(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.blue),
                  onPressed: () async {
                    // Check if user is authenticated
                    final currentUser = Supabase.instance.client.auth.currentUser;
                    if (currentUser == null) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text('Please login first'),
                        ),
                      );
                      return;
                    }

                    try {
                      // Upload image if selected
                      if (imageprovider.imageFile != null) {
                        await imageprovider.addImage();
                      }

                      // Create and save user data with authenticated user ID
                      final save = Usermodel(
                        password: password.text,
                        username: username.text,
                        userId: currentUser.id, // user_id in database
                        // id is not set - it's auto-generated by database
                      );

                      // Wait for data to be saved
                      await value.addDatas(save);

                      // Only navigate after successful save
                      if (context.mounted) {
                        Navigator.pop(context);
                      }
                    } catch (e) {
                      // Show error to user
                      if (context.mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(content: Text('Error saving data: $e')),
                        );
                      }
                    }
                  },
                  child: Text('save'))
            ],
          ),
        )),
      ),
    );
  }
}
